<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>6b4f7ea5-ceef-4904-87eb-636cd7ce5e8b</UserSecretsId>
        <AspireUseCliBundle>true</AspireUseCliBundle>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting" Version="13.5.3" />
        <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
        <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
        <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" Version="13.5.0" />
        <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="10.0.12" />
        <PackageReference Include="Refit.HttpClientFactory" Version="15.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Faber.Api\Faber.Api.csproj" />
        <ProjectReference Include="..\..\Jobs\Faber.Bootstrap\Faber.Bootstrap.csproj" />
        <ProjectReference Include="..\..\Jobs\Faber.Migrations\Faber.Migrations.csproj" />
    </ItemGroup>

</Project>
