<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Faber.Modules.Identity.PublicApi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Faber.Modules.Identity.Domain\Faber.Modules.Identity.Domain.csproj"/>
    </ItemGroup>

</Project>
