<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ErrorOr" Version="2.1.1" />
        <PackageReference Include="FastEndpoints" Version="8.3.0" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
        <PackageReference Include="Refit" Version="15.2.0" />
        <PackageReference Include="Refit.HttpClientFactory" Version="15.2.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Common\Faber.Modules.Common.PublicApi\Faber.Modules.Common.PublicApi.csproj"/>
        <ProjectReference Include="..\..\Vault\Faber.Modules.Vault.PublicApi\Faber.Modules.Vault.PublicApi.csproj"/>
        <ProjectReference Include="..\Faber.Modules.Identity.Domain\Faber.Modules.Identity.Domain.csproj"/>
        <ProjectReference Include="..\Faber.Modules.Identity.Infrastructure\Faber.Modules.Identity.Infrastructure.csproj"/>
        <ProjectReference Include="..\Faber.Modules.Identity.PublicApi\Faber.Modules.Identity.PublicApi.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Features\"/>
    </ItemGroup>


</Project>
