<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RollForward>Major</RollForward>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
        <PackageReference Include="Shouldly" Version="4.3.0"/>
        <PackageReference Include="Testcontainers" Version="4.15.0" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\..\src\api\Modules\Vault\Faber.Modules.Vault.Application\Faber.Modules.Vault.Application.csproj"/>
        <ProjectReference Include="..\..\..\..\..\src\api\Modules\Vault\Faber.Modules.Vault.PublicApi\Faber.Modules.Vault.PublicApi.csproj"/>
    </ItemGroup>

</Project>
