import { signal } from '@angular/core';
import { vi } from 'vitest';
import { NoticeVariant, PreviewStatus, ResumesStore, SaveStatus, SectionBulkRequest, SyncErrorKind } from '../../modules/resumes/resumes-store';

export function mockResumesStore(): Partial<ResumesStore> {
  return {
    resume: signal(null),
    isLoading: signal(false),
    error: signal(null),
    noticeVariant: signal<NoticeVariant>('error'),
    preview: signal(null),
    previewRevision: signal<number | null>(null),
    previewGeneration: signal<number | null>(null),
    previewStatus: signal<PreviewStatus>('unavailable'),
    hasRenderedPreview: signal(false),
    saveStatus: signal<SaveStatus>('idle'),
    syncErrorKind: signal<SyncErrorKind>(null),
    isDownloading: signal(false),
    canDownload: signal(true),
    requestedSection: signal(null),
    requestedAllSections: signal<SectionBulkRequest | null>(null),
    person: signal(undefined),
    summary: signal(''),
    hobbies: signal(''),
    localization: signal(''),
    educations: signal([]),
    experiences: signal([]),
    skills: signal([]),
    languages: signal([]),
    links: signal([]),
    courses: signal([]),
    loadResume: vi.fn(),
    clearError: vi.fn(),
    refreshPreview: vi.fn(),
    confirmPreviewRendered: vi.fn(),
    reportPreviewRenderFailure: vi.fn(),
    requestSection: vi.fn(),
    requestAllSections: vi.fn(),
    setPreviewEnabled: vi.fn(),
    downloadPdf: vi.fn(),
    updatePerson: vi.fn(),
    updateSummary: vi.fn(),
    updateHobbies: vi.fn(),
    updateLocalization: vi.fn(),
    addEducation: vi.fn(),
    updateEducation: vi.fn(),
    deleteEducation: vi.fn(),
    reorderEducations: vi.fn(),
    addExperience: vi.fn(),
    updateExperience: vi.fn(),
    deleteExperience: vi.fn(),
    reorderExperiences: vi.fn(),
    addSkill: vi.fn(),
    updateSkill: vi.fn(),
    deleteSkill: vi.fn(),
    reorderSkills: vi.fn(),
    addLanguage: vi.fn(),
    updateLanguage: vi.fn(),
    deleteLanguage: vi.fn(),
    reorderLanguages: vi.fn(),
    addLink: vi.fn(),
    updateLink: vi.fn(),
    deleteLink: vi.fn(),
    reorderLinks: vi.fn(),
    addCourse: vi.fn(),
    updateCourse: vi.fn(),
    deleteCourse: vi.fn(),
    reorderCourses: vi.fn(),
  } satisfies Partial<ResumesStore>;
}
