<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
        <PackageReference Include="Shouldly" Version="4.3.0"/>
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\api\Aspire\Faber.AppHost\Faber.AppHost.csproj"/>
        <ProjectReference Include="..\..\..\src\api\Jobs\Faber.Migrations\Faber.Migrations.csproj"/>
        <ProjectReference Include="..\..\..\src\api\Modules\Resumes\Faber.Modules.Resumes.Infrastructure\Faber.Modules.Resumes.Infrastructure.csproj"/>
        <ProjectReference Include="..\..\..\src\api\Modules\Identity\Faber.Modules.Identity.Infrastructure\Faber.Modules.Identity.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
